pull_request_rules:
  - name: Automatic merge on docker image updates
    conditions:
      - author=dependabot[bot]
      - check-success=build
      - label=dependencies
      - label=docker
      - dependabot-dependency-name=php
    actions:
      merge:
        method: merge
